### ISSUE TITLE
error on fedora

### ISSUE THREAD

**Issue by DansNewLegs** [tabletseeker/readcomic_dl#2]
I am getting this error on fedora 39. I have installed all dependencies. 

init_dialog: dlg_parse_rc
use_scrollbar:27: unknown variable

**Comment by DansNewLegs** [comment]
I commented out use scrollbar in ~/.dialogrc and it works now.

**Comment by tabletseeker** [comment]
Interesting, that seems to be specific to the fedora package of dialog.

Just out of curiosity, could you post a default generated dialogrc?

Simply execute `dialog --create-rc test`

Also, is the dialog black/white theme being displayed correctly?
