### ISSUE TITLE
unknown variable error

### ISSUE THREAD

**Issue by kgeo** [tabletseeker/readcomic_dl#3]
I'm in Windows 10 Ubuntu WSL. Followed the Usage guide. running the script `bash readcomic_dl/readcomic_dl` results in an endless error loop that prints 

`init_dialog: dlg_parse_rc`
`use_scrollbar:27: unknown variable`

repeatedly.

**Comment by tabletseeker** [comment]
Hi there,

WSL is known to cause dialog and tty related issues.

Please provide the output of `bash -x readcomic_dl` after a completed run.

I updated the script (and readme) to prevent potential path issues, but make sure you cd into the readcomic_dl directory before executing.

**Comment by kgeo** [comment]
the script does not stop. I have to CTRL-C it. I did cd into the directory as you said. Here is the last two iterations of what you suggested (with -x) before killing it:
~~~
init_dialog: dlg_parse_rc
+ true
++ dialog --title 'Comic URL' --inputbox 'Enter the URL of your comic'\''s main page:' 8 50
++ tr -d ' '
+ url='use_scrollbar:27:unknownvariable

init_dialog:dlg_parse_rc'
+ [[ use_scrollbar:27:unknownvariable

init_dialog:dlg_parse_rc =~ https://readcomiconline.li/Comic/(.*?) ]]
+ dialog --title 'Error Input' --msgbox 'This script exclusively supports main page links from readcomiconline.li \nPlease try again!' 8 28
use_scrollbar:27: unknown variable

init_dialog: dlg_parse_rc
+ true
++ dialog --title 'Comic URL' --inputbox 'Enter the URL of your comic'\''s main page:' 8 50
++ tr -d ' '
+ url='use_scrollbar:27:unknownvariable

init_dialog:dlg_parse_rc'
+ [[ use_scrollbar:27:unknownvariable

init_dialog:dlg_parse_rc =~ https://readcomiconline.li/Comic/(.*?) ]]
+ dialog --title 'Error Input' --msgbox 'This script exclusively supports main page links from readcomiconline.li \nPlease try again!' 8 28
use_scrollbar:27: unknown variable

init_dialog: dlg_parse_rc
+ true
++ tr -d ' '
++ dialog --title 'Comic URL' --inputbox 'Enter the URL of your comic'\''s main page:' 8 50
~~~

**Comment by tabletseeker** [comment]
Pretty sure WSL is causing this. The script works fine, I just tested it on Ubuntu.

Maybe try terminator or gnome-terminal to start the script and set scrolling to infinite. Otherwise you'll probably have to use a virtual machine or straight Linux install.

**Comment by nbycoder** [comment]
Hi! I'm currently running Pop_OS! And I have this exact error... Running on both Cosmic Terminal & Gnome Terminal...
